### ISSUE TITLE
error while bulid in VSCode

### ISSUE THREAD

**Issue by Elektrickser** [c5n/oh-ez-touch#23]
Hi,

when i will build des code, i become some errors:

https://pastebin.com/RhNzt41K

Windows 10
VSCode
Platformio
Expressif-Framework 
all module are actual

**Comment by c5n** [comment]
Hi Elektrickser
the error message in the log looks weird, somehow he wants to compile fragments of a string. 
Unfortunately I have linux only. Maybe you can workaround this issue by firing up a ubuntu vm?

I will try to make a binary release in future for easier installation.

c5n

**Comment by Elektrickser** [comment]
The Issue is in platformio/Expressif-Framework.

When i take the steps on an Ubuntu-PC its ok.

I close this Issue.
